### ISSUE TITLE
Chrome just autoupdates it anyway

### ISSUE THREAD

**Issue by nadir121** [03stevensmi/Google-Translate-Previous-Extension-2.0.13-#1]
Chrome will autoupdate it even if you change the URL it gets the update from

**Comment by 03stevensmi** [comment]
> Chrome will autoupdate it even if you change the URL it gets the update from

Fixed It! Tested it in brave browser and it works and it no longer auto updates!
Please remove the translate extension and use the new zip file from the release page.
Make sure to follow the new tutorial if you get stuck.

Thanks man,
I hope this helps you and everyone else out a bit.
Enjoy!
;)
